Feat/tips_cards
XPEHO/UDSP59 pull request #42
Opened 2023-11-06 13:01 UTC by NyraSama

# Description
What are changes related to ?
Add a dynamic set of cards which we can switch on the Homepage using JSON.

# Tests
How has it been tested ?

- [X] Manually
- [ ] Automated tests
- [ ] QA
- [ ] Other

2023-11-06 13:19 UTC, SDecambray approved these changes
LGTM

2023-11-06 13:26 UTC, PiotrFLEURY requested changes

2023-11-06 13:26 UTC, PiotrFLEURY commented on lib/features/tips_card_switcher.dart
> +    debugPrint('state2: $state2');
what are state1 and state2 ? 

instead of using random directly inside the UI you should use a state manager like Riverpod

2023-11-06 13:26 UTC, PiotrFLEURY commented on lib/features/tips_card_switcher.dart
> +          debugPrint('state2: $state2');
same as before, state1 and state2 are obccure magic

2023-11-07 09:50 UTC, PiotrFLEURY approved these changes
LGTM

2023-11-07 09:51 UTC, merged